# Generated by Django 5.0.4 on 2024-05-04 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barkyapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('appointment_date', models.DateField(verbose_name='Appointment date')),
                ('appointment_time', models.TimeField(verbose_name='Appointment time')),
                ('status', models.BooleanField(default=False)),
                ('doctor', models.CharField(choices=[('WS', 'Watson'), ('BK', 'Brooks'), ('GW', 'Greenway'), ('HT', 'Hiliton')], default='WS', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('patient', models.CharField(max_length=255)),
                ('age', models.IntegerField(blank=True)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PatientHistory',
            fields=[
                ('history_number', models.IntegerField(primary_key=True, serialize=False)),
                ('admit_date', models.DateField(auto_now_add=True, verbose_name='Admit Date')),
                ('symptons', models.TextField(blank=True)),
                ('department', models.CharField(choices=[('CL', 'Cardiologist'), ('DL', 'Dermatologists'), ('EMC', 'Emergency Medicine Specialists'), ('IL', 'Immunologists'), ('AL', 'Anesthesiologists'), ('CRS', 'Colon and Rectal Surgeons')], default='EMC', max_length=5)),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Release Date')),
                ('patient_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Bookmark',
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='barkyapi.patient'),
        ),
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
