# Generated by Django 5.0.4 on 2024-05-05 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barkyapi', '0002_appointment_patient_patienthistory_delete_bookmark_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='patienthistory',
            name='symptons',
            field=models.CharField(max_length=255),
        ),
    ]
